### ISSUE TITLE
Dynamic images ? 

### ISSUE THREAD

**Issue by rbravo86** [zxcodes/Weatherify-Web#1]
Dynamic images based on the city would be great instead of hardcoding the query.

https://github.com/zxcodes/Weatherify-Web/blob/bbe54d25155ff1d0587534c0baa17bb7241a5cb7/src/components/Search/Search.jsx#L30

**Comment by zxcodes** [comment]
Thanks for the suggestion but I've already tried that and it didn't work well. And that's because the API doesn't return that accurate results for a few cities. So I let random images be as background.
